### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by asdat3** [breuerfelix/twitch-viewer-bot#4]
Hey,
just tested it:
thoose two modules are missing in the requirements.txt:
```
click
python-dateutil
```

and it says current viewer count: 0 all the time, nothing´s happening

**Comment by breuerfelix** [comment]
thanks for noting, i will add those to the requirements.txt when i am back home after holidays.

yeah it is not working since you need to provide some proxies. but even with proxies it doesn't work. please have a look at the readme :)
